#!/usr/bin/env php
<?php

// set to run indefinitely if needed
set_time_limit(0);

/* Optional. It’s better to do it in the php.ini file */
date_default_timezone_set('America/Sao_Paulo');

// include the composer autoloader
require_once __DIR__ . '/../vendor/autoload.php';

// import the Symfony Console Application
use Symfony\Component\Console\Application;

$app = new Application('Todo', '1.0.0');
$app->add(new \Task\Command\SelfUpdateCommand());
$app->add(new \Task\Command\TaskAddCommand());
$app->add(new \Task\Command\TaskToggleCommand());
$app->add(new \Task\Command\TaskListCommand());
$app->add(new \Task\Command\TaskRemoveCommand());
$app->add(new \Task\Command\TaskHelpCommand());
$app->add(new \Task\Command\TaskSearchCommand());
$app->add(new \Task\Command\TaskConfigCommand());
$app->add(new \Task\Command\TaskUpdateCommand());
$app->add(new \Task\Command\TaskInitCommand());
$app->run();
